dbinstances:
  instance1:
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: true
    engine: postgres
    monitoring:
      enabled: true
    secrets:
      adminUser: admin
      adminPassword: IamAdmin
    instanceVars:
      TEST: TEST
  instance2:
    engine: mysql
    monitoring:
      enabled: true
    secrets:
      adminUser: adminUser
      adminPassword: adminAdmin
