---
apiVersion: v2
type: application
name: db-operator
version: 3.0.0
description: This operator lets you manage databases in a Kubernetes native way, even if they are not deployed to Kubernetes

# All supported k8s versions are in the test:
# https://github.com/db-operator/charts/blob/main/.github/workflows/integration-test.yaml
kubeVersion: ">= 1.32-prerelease"
appVersion: "0d275aee19275f7bc7706e3705b331d81dc1c12e"

home: https://github.com/db-operator
maintainers:
  - name: Nikolai Rodionov
    email: iam@allanger.xyz
    url: https://badhouseplants.net
sources:
  - https://github.com/db-operator/db-operator
keywords:
  - database
  - mysql
  - postgres
