---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "db-operator-psql-test.name" . }}-mysql-test-script
  labels:
    {{- include "db-operator-psql-test.labels" . | nindent 4 }}
data:
  random: {{ randAlphaNum 10 | toString}}
